project_id = "mnhtpdsgxlyqppzyevvl"

[functions.generate-logo]
verify_jwt = false

[functions.find-suppliers]
verify_jwt = false

[functions.generate-menu]
verify_jwt = false

[functions.create-chef-account]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.auto-create-account]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.get-auth-users-count]
verify_jwt = false

[functions.lookup-pending-profile]
verify_jwt = false
