import { useState, useCallback, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { ChefProfile, StepId } from '@/types/onboarding';

const SESSION_TOKEN_KEY = 'pending_profile_session_token';

interface PendingProfileData {
  id: string;
  email: string;
  current_step: string;
  session_token: string;
}

// Map onboarding types to DB enum values
function mapFoodSafetyStatus(status: string): 'have_certificate' | 'getting_certificate' | 'need_help' {
  const map: Record<string, 'have_certificate' | 'getting_certificate' | 'need_help'> = {
    'has_certificate': 'have_certificate',
    'needs_training': 'need_help',
  };
  return map[status] || 'need_help';
}

function mapKvkStatus(status: string): 'have_both' | 'in_progress' | 'need_help' {
  const map: Record<string, 'have_both' | 'in_progress' | 'need_help'> = {
    'kvk_nvwa_both': 'have_both',
    'kvk_only': 'in_progress',
    'none': 'need_help',
    'try_first': 'need_help',
  };
  return map[status] || 'need_help';
}

function mapPlanType(plan: string): 'starter' | 'growth' | 'pro' {
  const map: Record<string, 'starter' | 'growth' | 'pro'> = {
    'basic': 'starter',
    'pro': 'growth',
    'advanced': 'pro',
    'auto_recommend': 'starter',
  };
  return map[plan] || 'starter';
}

// Get session token from localStorage
function getSessionToken(): string | null {
  try {
    return localStorage.getItem(SESSION_TOKEN_KEY);
  } catch {
    return null;
  }
}

// Save session token to localStorage
function saveSessionToken(token: string): void {
  try {
    localStorage.setItem(SESSION_TOKEN_KEY, token);
  } catch (e) {
    console.error('Failed to save session token:', e);
  }
}

// Clear session token from localStorage
export function clearSessionToken(): void {
  try {
    localStorage.removeItem(SESSION_TOKEN_KEY);
  } catch (e) {
    console.error('Failed to clear session token:', e);
  }
}

export function usePendingProfile() {
  const [pendingProfileId, setPendingProfileId] = useState<string | null>(null);
  const [sessionToken, setSessionToken] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  // Load session token on mount
  useEffect(() => {
    const token = getSessionToken();
    if (token) {
      setSessionToken(token);
    }
  }, []);

  const savePendingProfile = useCallback(async (
    profile: ChefProfile,
    currentStep: StepId
  ): Promise<string | null> => {
    if (!profile.email) return null;
    
    setSaving(true);
    try {
      const profileData = {
        email: profile.email,
        phone: profile.phone || null,
        chef_name: `${profile.firstName || ''} ${profile.lastName || ''}`.trim() || null,
        business_name: profile.restaurantName || null,
        city: profile.city || null,
        address: profile.streetAddress 
          ? `${profile.streetAddress}, ${profile.zipCode || ''}, ${profile.city || ''}, ${profile.country || ''}`
          : null,
        cuisines: profile.primaryCuisines || [],
        dish_types: profile.dishTypes || [],
        availability: profile.availabilityBuckets || [],
        service_type: (profile.serviceType || 'unsure') as 'delivery' | 'pickup' | 'both' | 'unsure',
        food_safety_status: profile.foodSafetyStatus ? mapFoodSafetyStatus(profile.foodSafetyStatus) : null,
        kvk_status: profile.kvkStatus ? mapKvkStatus(profile.kvkStatus) : null,
        plan: profile.plan ? mapPlanType(profile.plan) : 'starter',
        logo_url: profile.logoUrl || null,
        current_step: currentStep,
      };

      const currentToken = getSessionToken();

      // If we have a session token, try to update existing profile
      if (currentToken) {
        // Use custom header to pass session token for RLS
        const { data: existing, error: selectError } = await supabase
          .from('pending_profiles')
          .select('id, session_token')
          .eq('email', profile.email)
          .maybeSingle()
          .setHeader('x-session-token', currentToken);

        if (existing && !selectError) {
          // Update existing
          const { error } = await supabase
            .from('pending_profiles')
            .update(profileData)
            .eq('id', existing.id)
            .setHeader('x-session-token', currentToken);

          if (error) throw error;
          setPendingProfileId(existing.id);
          return existing.id;
        }
      }

      // Insert new profile - session_token is auto-generated by the database
      const { data, error } = await supabase
        .from('pending_profiles')
        .insert(profileData)
        .select('id, session_token')
        .single();

      if (error) throw error;
      
      // Save the new session token
      if (data.session_token) {
        saveSessionToken(data.session_token);
        setSessionToken(data.session_token);
      }
      
      setPendingProfileId(data.id);
      return data.id;
    } catch (error) {
      console.error('Error saving pending profile:', error);
      return null;
    } finally {
      setSaving(false);
    }
  }, []);

  const getPendingProfileByEmail = useCallback(async (email: string): Promise<PendingProfileData | null> => {
    try {
      const currentToken = getSessionToken();
      if (!currentToken) {
        // No token means we can't select (RLS will block)
        return null;
      }

      const { data, error } = await supabase
        .from('pending_profiles')
        .select('id, email, current_step, session_token')
        .eq('email', email)
        .maybeSingle()
        .setHeader('x-session-token', currentToken);

      if (error) throw error;
      return data;
    } catch (error) {
      console.error('Error fetching pending profile:', error);
      return null;
    }
  }, []);

  return {
    pendingProfileId,
    sessionToken,
    saving,
    savePendingProfile,
    getPendingProfileByEmail,
    clearSessionToken,
  };
}
